global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
        
  - job_name: "WMI Exporter"
    static_configs:
      - targets: ["192.168.0.58:9182"]