global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "Node Exporter 14"
    scheme: https
    static_configs:
      - targets: ["9a3f-196-2-66-6.ngrok.io"]
      
  - job_name: "WMI Exporter"
    static_configs:
      - targets: ["192.168.0.58:9182"]